 version: '3'
 services:
   react:
     build:
       context: ./react
     container_name: react_container
     ports:
       - 8080:8080
     volumes:
       - ../app:/app
     working_dir: /app
     tty: true
     # command: sh -c "cd assets && yarn install && yarn serve"

   go:
     build:
       context: ./go
     container_name: go_container
     ports:
       - 8082:8082
     volumes:
       - ../:/go/src
     working_dir: /go/src/app
     tty: true
     # command: fresh